version: '3'

services:
  redis:
    image: redis
    container_name: DoEx-redis-${NODE_ENV}
    restart: always
    volumes:
      - ../database/redis:/data
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
  postgres-db:
    image: 'postgres:11'
    container_name: 'DoEx-postgres-${NODE_ENV}'
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ../database/postgres/postgres-${NODE_ENV}:/var/lib/postgresql/data
    healthcheck:
      test: exit 0
  service:
    image: service:latest
    container_name: 'DoEx-service-${NODE_ENV}'
    restart: always
    command: ['yarn', 'serve']
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    tty: true
