version: "2.1"

services:
  shinev2-db:
    image: "postgres:11"
    container_name: "shinev2-${ENV}"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: shinev2_${ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_PATH}/shinev2-${ENV}:/var/lib/postgresql/data
    healthcheck:
      test: exit 0
